"""Alert preview page — a standalone HTML rendering of the exact alerts a
Telegram subscriber would receive. Zero keys, zero network, self-contained
(inline CSS, no external assets), openable in any browser or via the tiny
`python -m http.server` hint printed by the demo.

The committed examples/whale-alert-preview.html is regenerated by running
`whale-watch demo` from the repo root.
"""

from __future__ import annotations

import html as _html
from datetime import datetime, timezone
from pathlib import Path

from .enrich import tag_address
from .model import fmt_usd, short_addr

_CSS = """
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; padding: 32px 16px 64px; background: #0e1621; color: #e8e8e8;
       font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
.wrap { max-width: 720px; margin: 0 auto; }
header { text-align: center; margin-bottom: 28px; }
h1 { font-size: 26px; margin: 0 0 6px; }
.sub { color: #8ea2b8; font-size: 14px; }
.banner { background: #1c2b3a; border: 1px solid #2f4a5e; border-radius: 10px;
          padding: 10px 14px; font-size: 13px; color: #a8c7de; margin-bottom: 24px; }
.card { background: #17212b; border: 1px solid #253343; border-radius: 12px;
        padding: 16px 18px; margin-bottom: 16px; }
.card .head { display: flex; justify-content: space-between; align-items: baseline; }
.card .head .token { font-weight: 700; font-size: 15px; }
.badge { font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 999px; }
.badge.mega { background: #7a3b00; color: #ffd9a8; }
.badge.large { background: #3b4a7a; color: #c9d4ff; }
.badge.watch { background: #2a3a33; color: #b8e6c9; }
.flow { font-size: 19px; font-weight: 600; margin: 12px 0 6px; }
.flow .arrow { color: #6ab0f3; padding: 0 6px; }
.narrative { color: #c8d3de; font-size: 14px; margin: 0 0 12px; }
.meta { font-size: 12.5px; color: #8ea2b8; line-height: 1.7; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
.meta b { color: #b9c9d6; font-weight: 600; }
.tag-exchange { color: #ffb454; }
.ts { font-size: 12px; color: #6c849b; margin-top: 8px; text-align: right; }
footer { text-align: center; color: #5f768c; font-size: 12px; margin-top: 28px; }
"""


def render_preview(alerts: list, out_path: str | Path) -> Path:
    """Write the standalone preview page; returns the written path."""
    cards = "\n".join(_card(a) for a in alerts)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>whale-watch-tg — alert preview</title>
<style>{_CSS}</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>🐋 whale-watch-tg — alert preview</h1>
    <div class="sub">Exactly what a Telegram subscriber receives · {stamp}</div>
  </header>
  <div class="banner">⚠️ Demo page rendered from bundled <b>fixture transfers</b> — no real
  transactions, no network access, no API keys. Live alerts look the same.</div>
  {cards}
  <footer>whale-watch-tg · MIT · informational only, not trading advice</footer>
</div>
</body>
</html>
"""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding="utf-8")
    return out


def _card(alert) -> str:
    t = alert.transfer
    badge_cls = {"MEGA MOVE": "mega", "LARGE": "large"}.get(alert.rate_class, "watch")
    target = _html.escape(alert.to_tag or "an unknown address")
    from_tag = tag_address(t.from_addr)
    from_lbl = f"{from_tag[0]} · {from_tag[1]}" if from_tag else "untagged"
    to_tag = tag_address(t.to_addr)
    to_lbl = f"{to_tag[0]} · {to_tag[1]}" if to_tag else "untagged"
    return f"""<div class="card">
  <div class="head">
    <span class="token">🐋 {_html.escape(t.token)}</span>
    <span class="badge {badge_cls}">{_html.escape(alert.rate_class)}</span>
  </div>
  <div class="flow">{_html.escape(t.amount_fmt())} {_html.escape(t.token)} <span class="arrow">→</span> {target}</div>
  <p class="narrative">{_html.escape(alert.narrative)}</p>
  <div class="meta">
    <b>From</b> {short_addr(t.from_addr)} ({_html.escape(from_lbl)})<br>
    <b>To</b> {short_addr(t.to_addr)} ({_html.escape(to_lbl)})<br>
    <b>USD</b> ≈ {fmt_usd(t.value_usd)}<br>
    <b>Tx</b> {short_addr(t.tx_hash)} · block {t.block:,} · ethereum
  </div>
  <div class="ts">{_ts(t)} · demo fixture</div>
</div>"""


def _ts(t) -> str:
    if not t.timestamp:
        return "timestamp n/a"
    return datetime.fromtimestamp(t.timestamp, tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")